config/routes.rb
Rails.application.routes.draw do
  devise_for :users
	resources :posts do
		resources :comments
	end

	root 'posts#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :post
  belongs_to :user, optional: true
end

app/models/post.rb
class Post < ApplicationRecord

	extend FriendlyId
 	friendly_id :title, use: :slugged

	belongs_to :user
	has_many :comments, dependent: :destroy
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :posts
  has_many :comments
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

	def create

		@post = Post.friendly.find(params[:post_id])
		@comment = @post.comments.build(params[:comment].permit(:comment))
		@comment.user_id = current_user.id if current_user
		@comment.save

		if @comment.save
			redirect_to post_path(@post)
		else
			render 'new'
		end
	end

	def edit
		@post = Post.friendly.find(params[:post_id])
		@comment = @post.comments.find(params[:id])
	end

	def update
		@post = Post.friendly.find(params[:post_id])
		@comment = @post.comments.find(params[:id])

		if @comment.update(params[:comment].permit(:comment))
			redirect_to post_path(@post)
		else
			render 'edit'
		end
	end

	def destroy	
		@post = Post.friendly.find(params[:post_id])
		@comment = @post.comments.find(params[:id])
		@comment.destroy
		redirect_to post_path(@post)

	end

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
	before_action :authenticate_user!, except: [:index, :show]
	before_action :find_post, only: [:show, :edit, :update, :destroy]

	def index
		@posts = Post.paginate(:page => params[:page], per_page: 2).order("created_at DESC")
	end

	def show
		
	end

	def new

		@post = current_user.posts.build
	end

	def create
		@post = current_user.posts.build(post_params)

		if @post.save
			redirect_to @post
		else
			render 'new'
		end
	end

	def edit
	end

	def update
		if @post.update(post_params)
			redirect_to @post
		else
			render 'edit'
		end
	end

	def destroy
		@post.destroy
		redirect_to root_path
	end

	private

	def find_post
		@post = Post.friendly.find(params[:id])
	end

	def post_params
		params.require(:post).permit(:title, :content, :slug)
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/comments/_comment.html.erb
<div class="comment">
<div class="content">
	<p class="comment_content"><%= comment.comment %></p>
	<p class="comment_author"><%= comment.user.email %></p>
</div>
<div class="buttons">
	<%= link_to "Edit", edit_post_comment_path(comment.post, comment) %>
	<%= link_to "Delete", [comment.post, comment], method: :delete, data: {confirm: "Are you sure ?" } %>
	</div>

</div>

app/views/comments/_form.html.erb
<%= simple_form_for([@post, @post.comments.build]) do |f| %>
	<%= f.input :comment %>
	<%= f.submit  %>

<% end %>

app/views/comments/edit.html.erb
<h5>Edit reply</h5>

<%= simple_form_for([@post, @comment]) do |f| %>
	<%= f.input :comment %>
	<%= f.submit %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Forum</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link href="https://fonts.googleapis.com/css?family=Raleway:300,400,700" rel="stylesheet">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/normalize/7.0.0/normalize.css">
    <!-- Compiled and minified CSS -->
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.100.2/css/materialize.min.css">

  <link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet" integrity="sha384-wvfXpqpZZVQGK6TAh5PVlGOfQNHSoD2xbE+QkPxCAFlNEevoEH3Sl0sibVcOQVnN" crossorigin="anonymous">

  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js">

  <!-- Compiled and minified JavaScript -->
  <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.100.2/js/materialize.min.js"></script>
  </head>

  <body>
  <header class="main_header">
  <div class="wrapper">
        <div id="logo">
       <p> <%= link_to "Learn Rails WithMe", root_path %> </p>
        </div>
        <div class="buttons">
        <% if user_signed_in? %>
            <%= link_to "New Post", new_post_path, :class => 'button' %>
            <% else %>
            <%= link_to "Sign Up", new_user_registration_path, :class => 'button'%> 
            <%= link_to "Sign In", new_user_session_path, :class => 'button'%>
         <% end %>
         </div>
  </div>
  </header>

  <div class="wrapper">
  	<p class="notice"><%= notice %></p>
 		<p class="alert"><%= alert %></p>
  </div>
 		

  <div class="wrapper">

    <%= yield %>
      </div>
  <footer id="copyright">&copy; 2018 Learn Rails WithMe</footer>  

  </body>
</html>

app/views/layouts/devise.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Forum</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link href="https://fonts.googleapis.com/css?family=Raleway:300,400,700" rel="stylesheet">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/normalize/7.0.0/normalize.css">
    <!-- Compiled and minified CSS -->
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.100.2/css/materialize.min.css">
  
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js">

  <!-- Compiled and minified JavaScript -->
  <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.100.2/js/materialize.min.js"></script>
  </head>

  <body>
  <header class="main_header">
  <div class="wrapper">
        <div id="logo">
       <p> <%= link_to "Learn Rails WithMe", root_path %> </p>
        </div>
        <div class="buttons">
        <% if user_signed_in? %>
            <%= link_to "New Post", new_post_path, :class => 'button' %>
            <% else %>
            <%= link_to "Sign Up", new_user_registration_path, :class => 'button'%> 
            <%= link_to "Sign In", new_user_session_path, :class => 'button'%>
         <% end %>
         </div>
  </div>
  </header>

  <div class="wrapper">
  	<p class="notice"><%= notice %></p>
 		<p class="alert"><%= alert %></p>
  </div>
 		

  <div class="wrapper">
    <div class="row">
        <div class="col m6 offset-m3">
          <div class="card">
            <div class="card-content">
    <%= yield %>
      </div>
        </div>
      </div>
  </div>

  </div>

  </body>
</html>

app/views/posts/_form.html.erb
<%= simple_form_for @post do |f| %>
  <%= f.input :title, :class => 'post_title' %>
  <%= f.input :content %>
  <%= f.submit :class => 'button_update'%>
<% end %>

app/views/posts/edit.html.erb
<h5>Edit Post</h5>

<%= render 'form' %>

<%= link_to "Cancel", post_path %>

app/views/posts/index.html.erb
<div id="posts">
<% @posts.each do |post| %>
	<div class="post">
	<h2 class="title"><%= link_to post.title, post %></h2>
	<p class="date">Publised at <%= time_ago_in_words(post.created_at) %> by 
		<% if !post.user.nil? %>
  		<%= post.user.email %></p>
		<% end %> 
	</div>
	<% end %> <br/><br/>
	<%= will_paginate @posts %>
</div>

app/views/posts/new.html.erb
<h5>New post</h5>

<%= render 'form' %>

app/views/posts/show.html.erb
<div id="post_content">

<h1><%= @post.title %></h1>
<p><%= @post.content %></p>

<div id="comments">
	<i class="fa fa-comments-o">&nbsp;<%= @post.comments.count %> Comments</i>
	<%= render @post.comments %>

	<h6>Reply to thread</h6>
	<%= render "comments/form" %>
</div>

<hr>
<br/>

	<%= link_to "Edit" , edit_post_path(@post), :class => 'button_edit' %>
	<%= link_to "Delete", post_path(@post), :class => 'button_delete', method: :delete, data: { confirm: "Are you sure you want to do this?" } %>

</div>